### ISSUE TITLE
Error: Column `calc_CI(unlist(.data$estimate), CI)` is of unsupported class data.frame > 

### ISSUE THREAD

**Issue by marcelinodelacruz** [mastoffel/partR2#3]
Hi:
Running the example from the vignette doesnt work (it doesnt work with my own lmer model either). 
```
library(lme4)
Loading required package: Matrix
library(partR2)
data(biomass)
 modBM <- lmer(Biomass ~ Year + Temperature + Precipitation + 
              SpeciesDiversity + (1|Population), data = biomass)
 R2_BM <- partR2(modBM, data = biomass, R2_type = "marginal", nboot = 10)
```
It ends with this error:
```
Error: Column `calc_CI(unlist(.data$estimate), CI)` is of unsupported class data.frame
```

**Comment by mastoffel** [comment]
Hi,
 
Could you try 

`update.packages("dplyr")`

I think this is because I wrongly specified a dplyr minimum version of 0.8.3 as dependency, but partR2 is actually using a function from dplyr 1.0.0 .

**Comment by marcelinodelacruz** [comment]
That solved the error.
Thank you!
